export const tableOption = {
  border: true,
  index: true,
  addBtn: false,
  delBtn: false,
  editBtn: false,
  indexLabel: '序号',
  stripe: true,
  menuAlign: 'center',
  align: 'center',
  column: [
	  {
      label: '序号',
      prop: 'id',
      hide: true,
      span: 24,
      editDisabled: true,
      addDisplay: false,
    },
	  {
      label: '标题',
      prop: 'title',
      overHidden: true,
      span: 24,
    },
	  {
      label: '封面图片',
      prop: 'faceImg',
      height: 1,
      hide: true,
      overHidden: true,
      imgFullscreen: false,
      type: 'upload',
      imgType: 'card',
      listType: 'picture-img',
      span: 24,
    },
	  {
      label: '新闻类型',
      prop: 'newsType',      
      addDisplay: false,
      editVisdisplay: false,
      viewVisdiplay: false,
      span: 24,
      hide: true,
    },
    {
      label: '新闻类型',
      prop: 'newsTypeTitle',
      formslot: true,
      slot: true,
      addDisplay: true,
      editVisdisplay: true,
      span: 24,
    },
	  {
      label: '内容',
      prop: 'content',
      slot: true,
      span: 24,
      component: 'AvueUeditor',
      overHidden: true,
      formslot: true,
    },
	  {
      label: '作者',
      prop: 'author',
      slot: true,
      addDisabled: true,
      editDisabled: true,
    },
	  {
      label: '更新时间',
      prop: 'updateTime',
      editDisabled: true,
      addDisplay: false,
      span: 24,
      type: 'datetime',
      format: 'yyyy-MM-dd HH:mm',
      valueFormat: 'yyyy-MM-dd HH:mm:ss',
    },
	  {
      label: '创建时间',
      prop: 'createTime',
      editDisabled: true,
      addDisplay: false,
      span: 24,
      hide: true,
      type: 'datetime',
      format: 'yyyy-MM-dd HH:mm',
      valueFormat: 'yyyy-MM-dd HH:mm:ss',
    },
  ]
}
