export const tableOption = {
  border: true,
  index: true,
  addBtn: false,
  delBtn: false,
  editBtn: false,
  indexLabel: '序号',
  stripe: true,
  menuAlign: 'center',
  align: 'center',
  column: [
    {
      label: '编号',
      prop: 'id',
      hide: true,
      span: 24,
      editDisabled: true,
      addVisdiplay: false,
    },
    {
      label: '标题',
      prop: 'title',
      overHidden: true,
      span: 12,
    },
    {
      label: '封面图片',
      prop: 'faceImg',
      height: 1,
      hide: true,
      overHidden: true,
      imgFullscreen: false,
      type: 'upload',
      imgType: 'card',
      listType: 'picture-img',
      span: 24,
    },
    {
      label: '产品类型',
      prop: 'prodType',
      addVisdiplay: false,
      editVisdisplay: false,
      viewVisdiplay: false,
      span: 24,
      hide: true,
    },
    {
      label: '产品类型',
      prop: 'prodTypeTitle',
      formsolt: true,
      slot: true,
      addVisdiplay: true,
      editVisdisplay: true,
      span: 24,
    },
    {
      label: '价格',
      prop: 'price',
      type: 'Number',
      span: 12,
      rules: [{
        required: true,
        message: '请输入价格',
        trigger: 'blur'
      }],
    },
    {
      label: '淘宝链接',
      prop: 'tUrl',
      span: 12,
      overHidden: true,
    },
    {
      label: '产品介绍',
      prop: 'content',
      slot: true,
      span: 24,
      component: 'AvueUeditor',
      overHidden: true,
      formsolt: true,
    },
    {
      label: '操作用户',
      prop: 'author',
      slot: true,
      addDisabled: true,
      editDisabled: true,
    },
    {
      label: '更新时间',
      prop: 'updateTime',
      editDisabled: true,
      addVisdiplay: false,
      span: 24,
      type: 'datetime',
      format: 'yyyy-MM-dd HH:mm',
      valueFormat: 'yyyy-MM-dd HH:mm:ss',
    },
    {
      label: '创建时间',
      prop: 'createTime',
      editDisabled: true,
      addVisdiplay: false,
      span: 24,
      hide: true,
      type: 'datetime',
      format: 'yyyy-MM-dd HH:mm',
      valueFormat: 'yyyy-MM-dd HH:mm:ss',
    },
  ]
}
